---
settings:
  name: NetApp solutions for SAP
  internal:
    pdf_enabled: true
  prod:
    pdf_enabled: true
    harmony_enabled: false
  langs: de-de,us-en,es-es,fr-fr,it-it,pt-br,ja-jp,ko-kr,zh-cn,zh-tw
sidebar:
  entries:
  - title: Lösungen für SAP
    url: "/index.html"
  - title: Was ist neu
    url: "/whats-new.html"
  - section: bp
  - section: backup
  - section: lifecycle
  - section: briefs
  - title: Rechtliche Hinweise
    url: "/legal-notices.html"
product-family:
  name: NetApp solutions
  repo: netapp-solutions-family
