---
sidebar: sidebar 
permalink: backup/anf-cba-overview.html 
keywords: tr4959, 4959, overview, introduction 
summary: 'Dieser technische Bericht enthält Best Practices für SAP HANA Datensicherung auf Azure NetApp Files (ANF) mit NetApp BlueXP Cloud Backup für Applikationen (CBA). Das Dokument behandelt CBA-Konzepte, Best Practices für die Konfiguration und Beschreibungen von Betriebs-Workflows für Backup-, Wiederherstellungs- und Wiederherstellungsvorgänge.' 
---
= TR-4959: SAP HANA auf ANF - Backup und Recovery mit Cloud Backup für Applikationen
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./../media/


Nils Bauer, NetApp

[role="lead"]
Dieser technische Bericht enthält Best Practices für SAP HANA Datensicherung auf Azure NetApp Files (ANF) mit NetApp BlueXP Cloud Backup für Applikationen (CBA). Das Dokument behandelt CBA-Konzepte, Best Practices für die Konfiguration und Beschreibungen von Betriebs-Workflows für Backup-, Wiederherstellungs- und Wiederherstellungsvorgänge.

Unternehmen benötigen heutzutage eine kontinuierliche, unterbrechungsfreie Verfügbarkeit ihrer SAP-Applikationen. Sie erwarten konsistente Performance bei stetig wachsenden Datenmengen und routinemäßigen Wartungsaufgaben, wie z. B. System-Backups. Das Durchführen von Backups von SAP-Datenbanken ist eine wichtige Aufgabe, die erhebliche Performance-Auswirkungen auf das SAP-Produktionssystem haben kann.

Die Backup-Fenster verkürzen sich, während die zu sichernden Daten immer größer werden. Daher ist es schwierig, einen Zeitpunkt zu finden, an dem Backups mit minimalen Auswirkungen auf die Geschäftsprozesse durchgeführt werden können. Die Zeit, die zum Wiederherstellen und Wiederherstellen von SAP-Systemen benötigt wird, ist besorgt, da Ausfallzeiten von SAP-Produktions- und nicht produktiven Systemen minimiert werden müssen, um die Kosten für das Unternehmen zu senken.

link:anf-cba-backup-and-recovery-using-azure-netapp-files.html["Weiter: Backup und Recovery mit Azure NetApp Files."]
