---
sidebar: sidebar 
permalink: backup/hana-sc-vmware-smas-additional-info.html 
keywords: SAP HANA, VMware, SnapMirror active sync, SnapCenter, backup and recovery 
summary:  
---
= Zusätzliche Informationen und Versionsverlauf
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Dieser Artikel enthält Links zu weiteren Ressourcen für diese Lösung.

SnapCenter

link:hana-sc-generic-scope.html["Technischer Bericht: SAP HANA Backup and Recovery with SnapCenter"]

link:hana-sr-scs-system-replication-overview.html["TR-4719: SAP HANA System Replication – Backup und Recovery mit SnapCenter"]

link:../lifecycle/sc-copy-clone-introduction.html["TR-4667: Automatisierung von SAP HANA Systemkopie und Klonvorgängen mit SnapCenter"]

https://docs.netapp.com/us-en/snapcenter/index.html["SnapCenter-Softwaredokumentation"]

Aktive SnapMirror-Synchronisierung:

https://docs.netapp.com/us-en/ontap/snapmirror-active-sync/index.html["Übersicht über die aktive SnapMirror-Synchronisierung in ONTAP"]

https://knowledge.broadcom.com/external/article?legacyId=83370["NetApp ONTAP mit NetApp SnapMirror Active Sync mit VMware vSphere Metro Storage Cluster (vMSC)."]

https://docs.netapp.com/us-en/netapp-solutions/vmware/vmware-vmsc-with-smas.html["VMware vSphere Metro Storage-Cluster mit SnapMirror Active Sync"]

https://www.vmware.com/docs/vmware-vsphere-metro-storage-cluster-vmsc["VMware vSphere Metro Storage-Cluster (vMSC)"]

Versionsverlauf:

[cols="33%,33%,33%"]
|===
| Version | Datum | Kommentar 


| Version 1.0 | März 2025 | Ausgangsversion 
|===