---
sidebar: sidebar 
permalink: backup/hana-br-scs-additional-info.html 
keywords:  
summary:  
---
= Wo finden Sie weitere Informationen und Versionsverlauf
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Sehen Sie sich die folgenden Dokumente und/oder Websites an, um mehr über die in diesem Dokument beschriebenen Informationen zu erfahren:

* Seite „SnapCenter Ressourcen“
+
https://www.netapp.com/us/documentation/snapcenter-software.aspx["https://www.netapp.com/us/documentation/snapcenter-software.aspx"^]

* SnapCenter-Softwaredokumentation
+
https://docs.netapp.com/us-en/snapcenter/index.html["https://docs.netapp.com/us-en/snapcenter/index.html"^]

* TR-4667: Automatisierung von SAP Systemkopien mit dem SnapCenter
+
link:../lifecycle/sc-copy-clone-introduction.html["SAP Systemkopien mithilfe der SnapCenter automatisieren"]

* TR-4719: SAP HANA System Replication, Backup und Recovery mit SnapCenter
+
link:hana-sr-scs-system-replication-overview.html["SAP HANA System Replication, Backup and Recovery mit SnapCenter"]

* TR-4018: Integration von NetApp ONTAP-Systemen in SAP Landscape Management
+
https://www.netapp.com/pdf.html?item=/media/17195-tr4018pdf.pdf["https://www.netapp.com/pdf.html?item=/media/17195-tr4018pdf.pdf"^]

* TR-4646: SAP HANA Disaster Recovery with Storage Replication
+
https://www.netapp.com/pdf.html?item=/media/8584-tr4646pdf.pdf["https://www.netapp.com/pdf.html?item=/media/8584-tr4646pdf.pdf"^]





== Versionsverlauf

|===
| Version | Datum | Versionsverlauf des Dokuments 


| Version 1.0 | Juli 2017  a| 
* Erste Version.




| Version 1.1 | September 2017  a| 
* Der Abschnitt „Erweiterte Konfiguration und Anpassung“ wurde hinzugefügt.
* Kleinere Korrekturen.




| Version 2.0 | März 2018  a| 
* Updates zu SnapCenter 4.0:
Neue Ressource für das Datenvolumen
Verbesserte SnapRestore-Operation einer einzelnen Datei




| Version 3.0 | Januar 2020  a| 
* Der Abschnitt „SnapCenter-Konzepte und Best-Practices“ wurde hinzugefügt.
* Updates zu SnapCenter 4.3:
Automatische Erkennung
Automatisiertes Restore und Recovery
Unterstützung für HANA MDC mehrere Mandanten
Wiederherstellung eines Mandanten




| Version 3.1 | Juli 2020  a| 
* Kleinere Aktualisierungen und Korrekturen:
NFSv4-Unterstützung mit SnapCenter 4.3.1
Konfiguration der SSL-Kommunikation
Zentrale Plug-in-Implementierung für Linux auf IBM Power




| Version 3.2 | November 2020  a| 
* Die erforderlichen Benutzerberechtigungen für die Datenbank für HANA 2.0 SPS5 wurden hinzugefügt.




| Version 3.3 | Mai 2021  a| 
* Der Abschnitt SSL-hdbsql-Konfiguration wurde aktualisiert.
* Linux LVM-Unterstützung hinzugefügt.




| Version 3.4 | August 2021  a| 
* Die Konfigurationsbeschreibung für die automatische Ermittlung deaktivieren wurde hinzugefügt.




| Version 3.5 | Februar 2022  a| 
* Kleinere Updates zu SnapCenter 4.6 und Unterstützung von automatischer Erkennung für HANA-Systeme mit Systemreplizierung


|===