---
sidebar: sidebar 
permalink: backup/saphana-br-scs-where-to-find-additional-information.html 
keywords:  
summary:  
---
= Wo finden Sie weitere Informationen und Versionsverlauf
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./../media/


link:saphana-br-scs-advanced-configuration-and-tuning.html["Früher: Erweiterte Konfiguration und Optimierung."]

Sehen Sie sich die folgenden Dokumente und/oder Websites an, um mehr über die in diesem Dokument beschriebenen Informationen zu erfahren:

* Seite „SnapCenter Ressourcen“
+
https://www.netapp.com/us/documentation/snapcenter-software.aspx["https://www.netapp.com/us/documentation/snapcenter-software.aspx"^]

* SnapCenter-Softwaredokumentation
+
https://docs.netapp.com/us-en/snapcenter/index.html["https://docs.netapp.com/us-en/snapcenter/index.html"^]

* TR-4667: Automatisierung von SAP Systemkopien mit dem SnapCenter
+
https://www.netapp.com/pdf.html?item=/media/17111-tr4667pdf.pdf["https://www.netapp.com/pdf.html?item=/media/17111-tr4667pdf.pdf"^]

* TR-4719: SAP HANA System Replication, Backup und Recovery mit SnapCenter
+
https://www.netapp.com/pdf.html?item=/media/17030-tr4719pdf.pdf["https://www.netapp.com/pdf.html?item=/media/17030-tr4719pdf.pdf"^]

* TR-4018: Integration von NetApp ONTAP-Systemen in SAP Landscape Management
+
https://www.netapp.com/pdf.html?item=/media/17195-tr4018pdf.pdf["https://www.netapp.com/pdf.html?item=/media/17195-tr4018pdf.pdf"^]

* TR-4646: SAP HANA Disaster Recovery with Storage Replication
+
https://www.netapp.com/pdf.html?item=/media/8584-tr4646pdf.pdf["https://www.netapp.com/pdf.html?item=/media/8584-tr4646pdf.pdf"^]





== Versionsverlauf

|===
| Version | Datum | Versionsverlauf des Dokuments 


| Version 1.0 | Juli 2017  a| 
* Erste Version.




| Version 1.1 | September 2017  a| 
* Der Abschnitt „Erweiterte Konfiguration und Anpassung“ wurde hinzugefügt.
* Kleinere Korrekturen.




| Version 2.0 | März 2018  a| 
* Updates zu SnapCenter 4.0: Neue Datenvolumen Ressource verbessert Single File SnapRestore Betrieb




| Version 3.0 | Januar 2020  a| 
* Der Abschnitt „SnapCenter-Konzepte und Best-Practices“ wurde hinzugefügt.
* Updates für SnapCenter 4.3: Automatische Erkennung automatisierte Wiederherstellung und Recovery Unterstützung von HANA MDC mehrere Mandanten Restore-Vorgang mit einem Mandanten




| Version 3.1 | Juli 2020  a| 
* Kleinere Updates und Korrekturen: Unterstützung durch NFSv4 mit SnapCenter 4.3.1 Konfiguration der SSL-Kommunikation Zentrale Plugin-Bereitstellung für Linux auf IBM Power




| Version 3.2 | November 2020  a| 
* Die erforderlichen Benutzerberechtigungen für die Datenbank für HANA 2.0 SPS5 wurden hinzugefügt.




| Version 3.3 | Mai 2021  a| 
* Der Abschnitt SSL-hdbsql-Konfiguration wurde aktualisiert.
* Linux LVM-Unterstützung hinzugefügt.




| Version 3.4 | August 2021  a| 
* Die Konfigurationsbeschreibung für die automatische Ermittlung deaktivieren wurde hinzugefügt.




| Version 3.5 | Februar 2022  a| 
* Kleinere Updates zu SnapCenter 4.6 und Unterstützung von automatischer Erkennung für HANA-Systeme mit Systemreplizierung


|===