---
sidebar: sidebar 
permalink: bp/hana-asa-fc-host-setup_multi.html 
keywords: multipathing, fcp, hba, configure 
summary: Vor dem Einrichten des Hosts müssen NetApp SAN Host Utilities von der NetApp Support Site heruntergeladen und auf den HANA-Servern installiert werden. Die Dokumentation des Host Utility enthält Informationen zu zusätzlicher Software, die abhängig vom verwendeten FCP HBA installiert werden muss. 
---
= Einrichtung mehrerer Hosts
:allow-uri-read: 




== Einrichtung mehrerer Hosts

[role="lead"]
In diesem Kapitel wird beispielhaft die Einrichtung eines 2+1 SAP HANA-Mehrhostsystems beschrieben.



== LUN-Konfiguration für SAP HANA-Mehrhostsysteme

Das Linux LVM wird verwendet, um die Leistung zu steigern und LUN-Größenbeschränkungen zu beheben.

Beim SAP HANA-Host müssen Volume-Gruppen und logische Volumes erstellt und eingebunden werden, wie in der folgenden Tabelle angegeben.

|===
| Logisches Volume (LV) | Bereitstellungspunkt beim SAP HANA-Host | Hinweis 


| LV: FC5_data_mnt00001-vol | /hana/Data/FC5/mnt00001 | Montiert mit Speicheranschluss 


| LV: FC5_log_mnt00001-vol | /hana/log/FC5/mnt00001 | Montiert mit Speicheranschluss 


| LV: FC5_data_mnt00002-vol | /hana/Data/FC5/mnt00002 | Montiert mit Speicheranschluss 


| LV: FC5_log_mnt00002-vol | /hana/log/FC5/mnt00002 | Montiert mit Speicheranschluss 


| Externe NFS-Freigabe: FC5_shared | /hana/Shared | Gemountet auf allen Hosts mit NFS und /etc/fstab Eintrag 
|===

NOTE: SAP HANA-Multi-Host-Systeme erfordern die  `/hana/shared` Dateisystem, das mit allen Hosts eines Systems verbunden ist. In der Regel handelt es sich dabei um eine NFS-Freigabe, die von einem NFS-Server bereitgestellt wird. Es wird empfohlen, einen hochverfügbaren NFS-Server zu verwenden, z. B. ein NetApp FAS- oder AFF-System. Alternativ kann der integrierte NFS-Server eines Linux-Hosts verwendet werden.


NOTE: Mit der beschriebenen Konfiguration wird die  `/usr/sap/FC5` Das Verzeichnis, in dem das Standard-Home-Verzeichnis des Benutzers FC5adm gespeichert ist, befindet sich auf der lokalen Festplatte jedes HANA-Hosts. In einem Disaster Recovery-Setup mit festplattenbasierter Replikation empfiehlt NetApp die Verwendung von vier zusätzlichen LUNs für  `/usr/sap/FC5` Dateisystem jedes Hosts, sodass jeder Datenbankhost alle seine Dateisysteme auf dem zentralen Speicher hat.



=== Erstellen von LVM-Volume-Gruppen und logischen Volumes

. Initialisieren Sie alle LUNs als ein physisches Volume.
+
....
pvcreate /dev/mapper/svm1-FC5_data_mnt00001_1
pvcreate /dev/mapper/svm1-FC5_data_mnt00001_2
pvcreate /dev/mapper/svm1-FC5_data_mnt00002_1
pvcreate /dev/mapper/svm1-FC5_data_mnt00002_2
pvcreate /dev/mapper/svm1-FC5_log_mnt00001_1
pvcreate /dev/mapper/svm1-FC5_log_mnt00001_2
pvcreate /dev/mapper/svm1-FC5_log_mnt00002_1
pvcreate /dev/mapper/svm1-FC5_log_mnt00002_2
....
. Erstellen Sie die Volume-Gruppen für jede Daten- und Protokollpartition.
+
....
vgcreate FC5_data_mnt00001 /dev/mapper/svm1-FC5_data_mnt00001_1 /dev/mapper/svm1-FC5_data_mnt00001_2
vgcreate FC5_data_mnt00002 /dev/mapper/svm1-FC5_data_mnt00002_1 /dev/mapper/svm1-FC5_data_mnt00002_2
vgcreate FC5_log_mnt00001 /dev/mapper/svm1-FC5_log_mnt00001_1 /dev/mapper/svm1-FC5_log_mnt00001_2
vgcreate FC5_log_mnt00002 /dev/mapper/svm1-FC5_log_mnt00002_1 /dev/mapper/svm1-FC5_log_mnt00002_2
....
. Erstellen Sie für jede Daten- und Protokollpartition ein logisches Volume. Verwenden Sie eine Stripe-Größe, die der Anzahl der LUNs pro Volume-Gruppe entspricht (in diesem Beispiel sind es zwei), eine Stripe-Größe von 256 KB für Daten und 64.000 für das Protokoll. SAP unterstützt nur ein logisches Volume pro Volume-Gruppe.
+
....
lvcreate --extents 100%FREE -i 2 -I 256k --name vol FC5_data_mnt00001
lvcreate --extents 100%FREE -i 2 -I 256k --name vol FC5_data_mnt00002
lvcreate --extents 100%FREE -i 2 -I 64k --name vol FC5_log_mnt00002
lvcreate --extents 100%FREE -i 2 -I 64k --name vol FC5_log_mnt00001
....
. Scannen Sie bei allen anderen Hosts die physischen Volumes, Volume-Gruppen und Volume-Gruppen.


....
modprobe dm_mod
pvscan
vgscan
lvscan
....

NOTE: Wenn diese Befehle die Volumes nicht finden, ist ein Neustart erforderlich.

Zum Mounten der logischen Volumes müssen die logischen Volumes aktiviert sein. Um die Volumes zu aktivieren, führen Sie den folgenden Befehl aus:

....
vgchange -a y
....


=== Erstellen von Dateisystemen

Erstellen Sie das XFS-Dateisystem auf allen logischen Daten- und Protokollvolumes.

....
mkfs.xfs /dev/mapper/FC5_data_mnt00001-vol
mkfs.xfs /dev/mapper/FC5_data_mnt00002-vol
mkfs.xfs /dev/mapper/FC5_log_mnt00001-vol
mkfs.xfs /dev/mapper/FC5_log_mnt00002-vol
....


=== Erstellen von Bereitstellungspunkten

Erstellen Sie die erforderlichen Mount-Point-Verzeichnisse und legen Sie die Berechtigungen auf allen Worker- und Standby-Hosts fest:

....
sapcc-hana-tst:/ # mkdir -p /hana/data/FC5/mnt00001
sapcc-hana-tst:/ # mkdir -p /hana/log/FC5/mnt00001
sapcc-hana-tst:/ # mkdir -p /hana/data/FC5/mnt00002
sapcc-hana-tst:/ # mkdir -p /hana/log/FC5/mnt00002
sapcc-hana-tst:/ # mkdir -p /hana/shared
sapcc-hana-tst:/ # chmod -R 777 /hana/log/FC5
sapcc-hana-tst:/ # chmod -R 777 /hana/data/FC5
sapcc-hana-tst:/ # chmod 777 /hana/shared
....


=== Mounten Sie File-Systeme

Zur Montage des  `/hana/shared` Dateisysteme während des Systemstarts mithilfe der  `/etc/fstab` Konfigurationsdatei, fügen Sie die  `/hana/shared` Dateisystem in die  `/etc/fstab` Konfigurationsdatei jedes Hosts.

....
sapcc-hana-tst:/ # cat /etc/fstab
<storage-ip>:/hana_shared /hana/shared nfs rw,vers=3,hard,timeo=600, intr,noatime,nolock 0 0
....

NOTE: Alle Daten- und Protokolldateisysteme sind über den SAP HANA Storage Connector gemountet.

Um die Dateisysteme einzubinden, führen Sie folgenden Befehl aus: `mount -a` Befehl auf jedem Host.
