---
sidebar: sidebar 
permalink: bp/kvm-hana-storage.html 
keywords: NetApp storage, KVM, SAP HANA, NFS, FCP, ONTAP, storage configuration 
summary: Konfigurieren Sie NetApp -Speicher für SAP HANA auf SUSE KVM unter Verwendung der NFS- oder FCP-Protokolle.  Richten Sie Speicherverbindungen zwischen der VM und den NetApp ONTAP Systemen ein, um eine optimale Datenbankleistung zu erzielen. 
---
= NetApp Speicher für SAP HANA auf SUSE KVM konfigurieren
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Konfigurieren Sie NetApp -Speicher für SAP HANA auf SUSE KVM unter Verwendung der NFS- oder FCP-Protokolle.  Richten Sie Speicherverbindungen zwischen der VM und den NetApp ONTAP Systemen ein, um eine optimale Datenbankleistung zu erzielen.

Nachdem die VM mit SR-IOV-Netzwerkschnittstellen oder FCP-HBA-Ports konfiguriert wurde, konfigurieren Sie den Speicherzugriff innerhalb der VM.  Verwenden Sie den passenden NetApp SAP HANA-Konfigurationsleitfaden, der auf dem von Ihnen gewählten Speicherprotokoll basiert.



== Konfigurieren Sie NFS-Speicher für SAP HANA

Verwenden Sie die zuvor erstellten SR-IOV-Netzwerkschnittstellen, wenn das NFS-Protokoll für den SAP HANA-Speicher verwendet werden soll.

Folgen Sie den ausführlichen Konfigurationsschritten in der https://docs.netapp.com/us-en/netapp-solutions-sap/bp/hana-aff-nfs-introduction.html["SAP HANA on NetApp AFF Systems with NFS - Konfigurationsleitfaden"] Die

Wichtige Konfigurationsüberlegungen für KVM-Umgebungen:

* Verwenden Sie die zuvor für den Netzwerkverkehr konfigurierten virtuellen SR-IOV-Funktionen (VFs).
* Konfigurieren Sie Netzwerk-Bonding innerhalb der VM für Redundanz.
* Stellen Sie eine ordnungsgemäße Netzwerkumschaltung zwischen der VM und den NetApp -Speicher-SVMs sicher.
* Konfigurieren Sie Speichercontroller und VMs gemäß dem SAP HANA Konfigurationsleitfaden.




== FCP-Speicher für SAP HANA konfigurieren

Verwenden Sie die der VM zugewiesenen physischen HBA-Ports als PCI-Geräte, wenn das FCP-Protokoll für den SAP HANA-Speicher verwendet werden soll.

Wählen Sie die passende Konfigurationsanleitung für Ihr NetApp Speichersystem aus:

* Für NetApp AFF -Systeme: https://docs.netapp.com/us-en/netapp-solutions-sap/bp/hana-aff-fc-introduction.html["Technischer Bericht: SAP HANA on NetApp AFF Systems with Fibre Channel Protocol"]
* Für NetApp ASA -Systeme: https://docs.netapp.com/us-en/netapp-solutions-sap/bp/hana-asa-fc-introduction.html["Technischer Bericht: SAP HANA on NetApp ASA Systems with Fibre Channel Protocol"]


Wichtige Konfigurationsüberlegungen für KVM-Umgebungen:

* Verwenden Sie die physischen HBA-Ports, die der VM über PCI-Passthrough zugewiesen wurden.
* Konfigurieren Sie Multipathing innerhalb der VM für Redundanz über Fabric-Switches hinweg.
* Konfigurieren Sie Speichercontroller und VMs gemäß dem SAP HANA-Konfigurationsleitfaden.

