---
sidebar: sidebar 
permalink: bp/saphana-fas-nfs_sap_hana_data_volume_size.html 
keywords: sap, hana, data, volume, size, fas, nfs 
summary: Standardmäßig verwendet SAP HANA nur ein Daten-Volume pro SAP HANA Service. Aufgrund der maximalen Dateigröße des Dateisystems empfehlen wir, die maximale Größe des Datenträgers zu begrenzen. 
---
= Größe des SAP HANA Daten-Volumes
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./../media/


link:saphana-fas-nfs_i_o_stack_configuration_for_sap_hana.html["Früher: I/O-Stack-Konfiguration für SAP HANA"]

Standardmäßig verwendet SAP HANA nur ein Daten-Volume pro SAP HANA Service. Aufgrund der maximalen Dateigröße des Dateisystems empfehlen wir, die maximale Größe des Datenträgers zu begrenzen.

Um dies automatisch zu tun, setzen Sie den folgenden Parameter in ein `global.ini` Im Abschnitt `[persistence]`:

....
datavolume_striping = true
datavolume_striping_size_gb = 8000
....
Dadurch wird ein neues Daten-Volume erstellt, nachdem das Limit von 8 GB erreicht wurde. https://launchpad.support.sap.com/["SAP Note 240005 Frage 15"^] Bietet weitere Informationen.

link:saphana-fas-nfs_sap_hana_software_installation.html["Weiter: Installation der SAP HANA Software."]
