---
sidebar: sidebar 
permalink: bp/saphana-vsphere-fas-aff_pdf_link.html 
keywords: tr-4338, pdf, sap, hana, vmware, vsphere, aff, fas, all flash, fabric attached 
summary: 'Dieses Dokument zur Referenzarchitektur unterstützt Kunden bei der Konzipierung und Implementierung von SAP HANA Einzelhost- und Host-Lösungen auf VMware vSphere Virtual Machines (VMs) und NetApp FAS und All Flash FAS (AFF) Storage-Systemen.' 
---
= TR-4338: SAP HANA on VMware vSphere with NetApp – FAS and All Flash FAS Systems
:allow-uri-read: 
:firstname: : hardbreaks:
:author: : hardbreaks:
:authorinitials: :
:authors: : hardbreaks:
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Dieses Dokument zur Referenzarchitektur unterstützt Kunden bei der Konzipierung und Implementierung von SAP HANA Einzelhost- und Host-Lösungen auf VMware vSphere Virtual Machines (VMs) und NetApp FAS und All Flash FAS (AFF) Storage-Systemen. Diese Referenzarchitektur ist eine implementierte und dokumentierte Lösung, die auf Erfahrungen mit vorhandenen VMware und NetApp Kunden, Praxissimulationen und Validierungen im NetApp Engineering Lab basiert. Dieses Dokument unterstützt Kunden während des gesamten Lebenszyklus des Projekts, einschließlich Beurteilung der Anforderungen, Lösungsdesign, Installation und Administration.

Autoren:

Tobias Brandl, NetApp Erik Rieger, Bhumik Patel, VMware

link:https://www.netapp.com/pdf.html?item=/media/17192-tr4338pdf.pdf["https://www.netapp.com/pdf.html?item=/media/17192-tr4338pdf.pdf"]
