---
sidebar: sidebar 
permalink: bp/saphana_aff_fc_i_o_stack_configuration_for_sap_hana.html 
keywords: io, i/o, stack, configuration, database 
summary: Ab SAP HANA 1.0 SPS10 führte SAP Parameter ein, um das I/O-Verhalten anzupassen und die Datenbank für das verwendete Datei- und Speichersystem zu optimieren. 
---
= I/O-Stack-Konfiguration für SAP HANA
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Ab SAP HANA 1.0 SPS10 führte SAP Parameter ein, um das I/O-Verhalten anzupassen und die Datenbank für das verwendete Datei- und Speichersystem zu optimieren.

NetApp hat Performance-Tests durchgeführt, um die idealen Werte zu definieren. In der folgenden Tabelle sind die optimalen Werte aufgeführt, die aus den Leistungstests abgeleitet wurden.

|===
| Parameter | Wert 


| max_parallel_io_Requests | 128 


| Async_read_Submit | Ein 


| Async_write_submit_Active | Ein 


| Async_Write_Submit_Blocks | Alle 
|===
Für SAP HANA 1.0 bis SPS12 können diese Parameter während der Installation der SAP HANA-Datenbank eingestellt werden, wie in SAP Note beschrieben https://launchpad.support.sap.com/["2267798 – Konfiguration der SAP HANA Datenbank während der Installation mit hdbparam"^].

Alternativ können die Parameter nach der SAP HANA-Datenbankinstallation über die eingestellt werden `hdbparam` Framework:

....
SS3adm@stlrx300s8-6:/usr/sap/SS3/HDB00> hdbparam --paramset fileio.max_parallel_io_requests=128
SS3adm@stlrx300s8-6:/usr/sap/SS3/HDB00> hdbparam --paramset fileio.async_write_submit_active=on
SS3adm@stlrx300s8-6:/usr/sap/SS3/HDB00> hdbparam --paramset fileio.async_read_submit=on
SS3adm@stlrx300s8-6:/usr/sap/SS3/HDB00> hdbparam --paramset fileio.async_write_submit_blocks=all
....
Ab SAP HANA 2.0 `hdbparam` Ist veraltet und die Parameter werden in die verschoben `global.ini` Datei: Die Parameter können über SQL-Befehle oder SAP HANA Studio eingestellt werden. Weitere Informationen finden Sie im SAP-Hinweis https://launchpad.support.sap.com/["2399079: Beseitigung von hdbparam in HANA 2"^]. Die Parameter können auch im festgelegt werden `global.ini` Datei:

....
SS3adm@stlrx300s8-6: /usr/sap/SS3/SYS/global/hdb/custom/config> cat global.ini
…
[fileio]
async_read_submit = on
async_write_submit_active = on
max_parallel_io_requests = 128
async_write_submit_blocks = all
…
....
Verwenden Sie für SAP HANA 2.0 SPS5 und höher den `setParameter.py` Skript zum Festlegen der richtigen Parameter.

....
fc5adm@sapcc-hana-tst-03:/usr/sap/FC5/HDB00/exe/python_support>
python setParameter.py -set=SYSTEM/global.ini/fileio/max_parallel_io_requests=128
python setParameter.py -set=SYSTEM/global.ini/fileio/async_read_submit=on
python setParameter.py -set=SYSTEM/global.ini/fileio/async_write_submit_active=on
python setParameter.py -set=SYSTEM/global.ini/fileio/async_write_submit_blocks=all
....