---
sidebar: sidebar 
permalink: bp/saphana-fas-nfs_i_o_stack_configuration_for_sap_hana.html 
keywords: io, stack, configuration, sap, hana, fas, nfs 
summary: Ab SAP HANA 1.0 SPS10 führte SAP Parameter ein, um das I/O-Verhalten anzupassen und die Datenbank für die verwendeten Datei- und Speichersysteme zu optimieren. 
---
= I/O-Stack-Konfiguration für SAP HANA
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./../media/


link:saphana-fas-nfs_sap_hana_installation_preparations_for_nfsv4.html["Früher: Vorbereitungen für die Installation von SAP HANA auf NFSv4"]

Ab SAP HANA 1.0 SPS10 führte SAP Parameter ein, um das I/O-Verhalten anzupassen und die Datenbank für die verwendeten Datei- und Speichersysteme zu optimieren.

NetApp hat Performance-Tests durchgeführt, um die idealen Werte zu definieren. In der folgenden Tabelle sind die optimalen Werte aufgeführt, die aus den Leistungstests abgeleitet wurden.

|===
| Parameter | Wert 


| max_parallel_io_Requests | 128 


| Async_read_Submit | Ein 


| Async_write_submit_Active | Ein 


| Async_Write_Submit_Blocks | Alle 
|===
Bei SAP HANA 1.0 Versionen bis SPS12 können diese Parameter während der Installation der SAP HANA Datenbank eingestellt werden, wie in SAP Note beschrieben https://launchpad.support.sap.com/["2267798: Konfiguration der SAP HANA Datenbank während der Installation mit hdbparam"^].

Alternativ können die Parameter nach der SAP HANA-Datenbankinstallation über die eingestellt werden `hdbparam` Framework:

....
nf2adm@sapcc-hana-tst-06:/usr/sap/NF2/HDB00> hdbparam --paramset fileio.max_parallel_io_requests=128
nf2adm@sapcc-hana-tst-06:/usr/sap/NF2/HDB00> hdbparam --paramset fileio.async_write_submit_active=on
nf2adm@sapcc-hana-tst-06:/usr/sap/NF2/HDB00> hdbparam --paramset fileio.async_read_submit=on
nf2adm@sapcc-hana-tst-06:/usr/sap/NF2/HDB00> hdbparam --paramset fileio.async_write_submit_blocks=all
....
Ab SAP HANA 2.0 `hdbparam` Wurde veraltet und die Parameter wurden in verschoben `global.ini`. Die Parameter können mit SQL-Befehlen oder SAP HANA Studio eingestellt werden. Weitere Informationen finden Sie im SAP-Hinweis https://launchpad.support.sap.com/["2399079: Beseitigung von hdbparam in HANA 2"^]. Sie können die Parameter auch in global.ini einstellen, wie im folgenden Text dargestellt:

....
nf2adm@stlrx300s8-6: /usr/sap/NF2/SYS/global/hdb/custom/config> cat global.ini
…
[fileio]
async_read_submit = on
async_write_submit_active = on
max_parallel_io_requests = 128
async_write_submit_blocks = all
…
....
Seit SAP HANA 2.0 SPS5, dem `setParameter.py` Skript kann verwendet werden der Satz die richtigen Parameter:

....
nf2adm@sapcc-hana-tst-06:/usr/sap/NF2/HDB00/exe/python_support>
python setParameter.py -set=SYSTEM/global.ini/fileio/max_parallel_io_requests=128
python setParameter.py -set=SYSTEM/global.ini/fileio/async_read_submit=on
python setParameter.py -set=SYSTEM/global.ini/fileio/async_write_submit_active=on
python setParameter.py -set=SYSTEM/global.ini/fileio/async_write_submit_blocks=all
....
link:saphana-fas-nfs_sap_hana_data_volume_size.html["Next-Generation-Volume von SAP HANA"]
