---
sidebar: sidebar 
permalink: bp/saphana_aff_fc_sap_hana_storage_connector_api.html 
keywords: api, failover, ha, high availability 
summary: Ein Storage Connector ist nur in Umgebungen mit mehreren Hosts mit Failover-Funktionen erforderlich. SAP HANA bietet bei der Einrichtung mehrerer Hosts eine Hochverfügbarkeitsfunktionen, mit der ein Failover eines SAP HANA-Datenbankhosts auf einen Standby-Host möglich ist. In diesem Fall wird auf die LUNs des ausgefallenen Hosts zugegriffen und vom Standby-Host verwendet. 
---
= SAP HANA Storage-Connector-API
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Ein Storage Connector ist nur in Umgebungen mit mehreren Hosts mit Failover-Funktionen erforderlich. SAP HANA bietet bei der Einrichtung mehrerer Hosts eine Hochverfügbarkeitsfunktionen, mit der ein Failover eines SAP HANA-Datenbankhosts auf einen Standby-Host möglich ist.

In diesem Fall wird auf die LUNs des ausgefallenen Hosts zugegriffen und vom Standby-Host verwendet. Der Speicher-Connector wird verwendet, um sicherzustellen, dass eine Speicherpartition von jeweils nur einem Datenbank-Host aktiv zugegriffen werden kann.

In SAP HANA Konfigurationen mit mehreren Hosts und NetApp Storage kommt der von SAP bereitgestellte Standard-Storage Connector zum Einsatz. Der „SAP HANA Fibre Channel Storage Connector Admin Guide“ kann als Anhang zu gefunden werden https://service.sap.com/sap/support/notes/1900823["SAP-Hinweis 1900823"^].
