---
sidebar: sidebar 
permalink: lifecycle/lama-ansible-conclusion.html 
keywords: conclusion, additional information, version history 
summary: Die Integration eines modernen Automatisierungs-Frameworks wie Ansible in SAP Lama-Bereitstellungs-Workflows bietet Kunden eine flexible Lösung, die Standardanforderungen und komplexere Infrastrukturanforderungen erfüllt. 
---
= Schlussfolgerung
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./../media/


[role="lead"]
Die Integration eines modernen Automatisierungs-Frameworks wie Ansible in SAP Lama-Bereitstellungs-Workflows bietet Kunden eine flexible Lösung, die Standardanforderungen und komplexere Infrastrukturanforderungen erfüllt.



== Wo Sie weitere Informationen finden

Sehen Sie sich die folgenden Dokumente und/oder Websites an, um mehr über die in diesem Dokument beschriebenen Informationen zu erfahren:

* Sammlungen im NetApp Namespace
+
https://docs.ansible.com/ansible/latest/collections/netapp/index.html["https://docs.ansible.com/ansible/latest/collections/netapp/index.html"^]

* Dokumentation zu Ansible Integration und Beispiel Ansible Playbooks
+
https://github.com/sap-linuxlab/demo.netapp_ontap["https://github.com/sap-linuxlab/demo.netapp_ontap"^]

* Allgemeine Integration mit Ansible und NetApp
+
https://www.ansible.com/integrations/infrastructure/netapp["https://www.ansible.com/integrations/infrastructure/netapp"^]

* Blog zum Thema Integration von SAP Lama mit Ansible
+
https://blogs.sap.com/2020/06/08/outgoing-api-calls-from-sap-landscape-management-lama-with-automation-studio/["https://blogs.sap.com/2020/06/08/outgoing-api-calls-from-sap-landscape-management-lama-with-automation-studio/"^]

* SAP Landscape Management 3.0, Enterprise Edition Documentation
+
https://help.sap.com/doc/700f9a7e52c7497cad37f7c46023b7ff/3.0.11.0/en-US/4df88a8f418c5059e10000000a42189c.html["https://help.sap.com/doc/700f9a7e52c7497cad37f7c46023b7ff/3.0.11.0/en-US/4df88a8f418c5059e10000000a42189c.html#loio4df88a8f418c5059e10000000a42189c"^]

* SAP Lama-Dokumentation – Provider-Definitionen
+
https://help.sap.com/doc/700f9a7e52c7497cad37f7c46023b7ff/3.0.11.0/en-US/bf6b3e43340a4cbcb0c0f3089715c068.html["https://help.sap.com/doc/700f9a7e52c7497cad37f7c46023b7ff/3.0.11.0/en-US/bf6b3e43340a4cbcb0c0f3089715c068.html"^]

* SAP Lama-Dokumentation - Custom Hooks
+
https://help.sap.com/doc/700f9a7e52c7497cad37f7c46023b7ff/3.0.11.0/en-US/139eca2f925e48738a20dbf0b56674c5.html["https://help.sap.com/doc/700f9a7e52c7497cad37f7c46023b7ff/3.0.11.0/en-US/139eca2f925e48738a20dbf0b56674c5.html"^]

* SAP Lama Documentation – Konfigurieren von registrierten Skripten für SAP-Host-Agent
+
https://help.sap.com/doc/700f9a7e52c7497cad37f7c46023b7ff/3.0.11.0/en-US/250dfc5eef4047a38bab466c295d3a49.html["https://help.sap.com/doc/700f9a7e52c7497cad37f7c46023b7ff/3.0.11.0/en-US/250dfc5eef4047a38bab466c295d3a49.html"^]

* SAP Lama-Dokumentation - Parameter für benutzerdefinierte Operationen und benutzerdefinierte Haken
+
https://help.sap.com/doc/700f9a7e52c7497cad37f7c46023b7ff/3.0.11.0/en-US/0148e495174943de8c1c3ee1b7c9cc65.html["https://help.sap.com/doc/700f9a7e52c7497cad37f7c46023b7ff/3.0.11.0/en-US/0148e495174943de8c1c3ee1b7c9cc65.html"^]

* SAP Lama-Dokumentation - Adaptive Design
+
https://help.sap.com/doc/700f9a7e52c7497cad37f7c46023b7ff/3.0.11.0/en-US/737a99e86f8743bdb8d1f6cf4b862c79.html["https://help.sap.com/doc/700f9a7e52c7497cad37f7c46023b7ff/3.0.11.0/en-US/737a99e86f8743bdb8d1f6cf4b862c79.html"^]

* NetApp Produktdokumentation
+
https://www.netapp.com/support-and-training/documentation/["https://www.netapp.com/support-and-training/documentation/"^]





== Versionsverlauf

|===
| Version | Datum | Versionsverlauf des Dokuments 


| Version 1.0 | Januar 2023 | Erste Version 
|===