---
sidebar: sidebar 
permalink: lifecycle/lama-ansible-introduction.html 
keywords: tr4953, introduction, 4953, clone, copy, refresh automation 
summary: 'SAP Landscape Management (Lama) ermöglicht SAP-Systemadministratoren die Automatisierung von SAP-Systemprozessen. Dazu gehören ein lückenloses SAP-Systemklonen, -Kopien und -Aktualisierungen.' 
---
= TR-4953: NetApp SAP Landscape Management Integration Using Ansible
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
SAP Landscape Management (Lama) ermöglicht SAP-Systemadministratoren die Automatisierung von SAP-Systemprozessen. Dazu gehören ein lückenloses SAP-Systemklonen, -Kopien und -Aktualisierungen.

Autoren: Michael Schlosser, Nils Bauer, NetApp

NetApp bietet eine umfassende Auswahl an Ansible-Modulen, in denen SAP Lama über SAP Lama Automation Studio auf Technologien wie NetApp Snapshot und FlexClone zugreifen kann. Diese Technologien unterstützen die Vereinfachung und Beschleunigung von SAP Systemkopien, Kopien und Aktualisierungen.

Die Integration kann von Kunden genutzt werden, die NetApp Storage-Lösungen vor Ort ausführen, oder von Kunden, die NetApp Storage-Services bei Public-Cloud-Providern wie Amazon Web Services, Microsoft Azure oder der Google Cloud Platform nutzen.

In diesem Dokument wird die Konfiguration von SAP Lama mit NetApp Storage-Funktionen für SAP-Systemkopierungs-, Klon- und Aktualisierungsvorgänge mithilfe der Ansible-Automatisierung beschrieben.
