---
sidebar: sidebar 
permalink: lifecycle/sc-copy-clone-supported-infrastructure.html 
keywords: tr4667, 4667, SAP HANA, cloning, system refresh 
summary: NetApp Lösungen zur Optimierung des SAP Lifecycle Managements sind in SAP HANA Datenbank- und Lifecycle Management-Tools integriert und verbinden effiziente applikationsintegrierte Datensicherung mit der flexiblen Bereitstellung von SAP Testsystemen. 
---
= Unterstützte Infrastruktur und Szenarien
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Dieses Dokument behandelt Szenarien für SAP-Systemaktualisierung und -Klonen für SAP HANA-Systeme, die auf lokalen NetApp-Systemen, Amazon FSX für NetApp ONTAP-Systemen und Azure NetApp Files ausgeführt werden. Allerdings sind auf jeder Storage-Plattform nicht alle Features und Szenarien verfügbar. In der folgenden Tabelle sind die unterstützten Konfigurationen zusammengefasst.

Im Rahmen dieses Dokuments verwenden wir eine SAP HANA-Landschaft, die auf lokalen NetApp-Systemen mit NFS als Storage-Protokoll ausgeführt wird. Die meisten Workflow-Schritte sind auf den verschiedenen Plattformen identisch. Bei Unterschieden werden sie in diesem Dokument hervorgehoben.

[cols="25%,25%,25%,25%"]
|===
|  | *On-Premises NetApp Systeme* | *AWS FSX for NetApp ONTAP* | *Azure NetApp Files* 


| Speicherprotokoll und Dateisystem | Bare metal: NFS, FC mit XFS VMware: NFS-Einbindungen im Gastsystem, FC mit VMDKs und XFS | NFS | NFS 


| Thin-Klon (FlexClone) | Ja. | Ja. | Ja, aber nicht in SnapCenter integriert 


| Klonteilvorgang | Ja. | Ja. | Ja, aber nicht in SnapCenter integriert 


| Klonen von Primär | Ja. | Ja. | Ja. 


| Klonen von Backups an externen Standorten | Ja. | Ja. | Ja, Wiederherstellung auf neuem Volume aus dem ANF-Backup 


| Klonen am DR-Standort | Ja. | Ja. | Ja, aber nicht in SnapCenter integriert 
|===
Weitere Informationen zu SAP-Systemaktualisierungsvorgängen für HANA mit VMware VMFS und NetApp ASAr2-Systemen finden Sie unter  https://docs.netapp.com/us-en/netapp-solutions-sap/backup/hana-sc-vmfs-asar2sap-refresh.html["SAP-Systemaktualisierung"].
